### ISSUE TITLE
Landing page statistical error

### ISSUE THREAD

**Issue by MMeent** [PGPerfFarm/pgperffarm_server#68]
On the landing page of the project I find the following statistics block:

> 3 machines belonging to 2 users
> of which 13 reported in the last month 

Although I have little background in statistics, having 13 reporting machines out of 3 total seems like a counting error.

**Comment by YedilSerzhan** [comment]
Hi, this should be a textual error, it is supposed to mean:
> 3 machines belonging to 2 users
> of which 13 runs were reported in the last month
Really thank you for pointing it out, will fix it soon!
